name: Build and Publish raylight-cms

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: raylight-cms
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  RAYLIGHT_CMS_APP_SETTINGS: ${{ secrets.RAYLIGHT_CMS_APP_SETTINGS }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-versions: '8.0.x'

      - name: Setup App Settings
        run: |
          echo "$RAYLIGHT_CMS_APP_SETTINGS" > ./src/appsettings.json

      - name: Restore Solution
        run: dotnet restore ./src/raylight-cms.sln

      - name: Build Solution
        run: dotnet build ./src/raylight-cms.sln --configuration Release --no-restore

      - name: Publish Solution
        run: dotnet publish ./src/raylight-cms.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deploy Solution
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
